stages:
  - setup
  - testing

variables:
  CLIENT_DIR: "tests/frontend"
  BACKEND_DIR: "tests/backend"

setup-backend:
  stage: setup
  image: node:18
  script:
    - cd $BACKEND_DIR
    - npm install
  artifacts:
    paths:
      - $BACKEND_DIR/node_modules
    when: on_success
    expire_in: 1 hour

setup-frontend:
  stage: setup
  image: node:alpine
  script:
    - cd $CLIENT_DIR
    - npm install
  artifacts:
    paths:
      - $CLIENT_DIR/node_modules
    when: on_success
    expire_in: 1 hour

test_client:
  stage: testing
  image: node:alpine
  before_script:
    - cd $CLIENT_DIR
  script:
    - npm test

test_backend:
  stage: testing
  image: node:17
  before_script:
    - cd $BACKEND_DIR
  script:
    - npm test
