image: node:latest

stages:
  - test

backend_test:
  stage: test
  script:
    - cd backend/
    - npm install
    - npm test
  only:
    - develop
    - merge_requests

frontend_test:
  stage: test
  script:
    - cd frontend/
    - npm install
    - npm test
  only:
    - develop
    - merge_requests
