image: node:latest

stages:
  - test

backend_test:
  stage: test
  script:
    - cd backend/
    - npm install
    - npm test

frontend_test:
  stage: test
  script:
    - cd frontend/
    - npm install
